[package]
name = "tk-pool"
description = """
    Generic connection pool for tokio
"""
license = "MIT/Apache-2.0"
readme = "README.rst"
keywords = ["tokio", "connection-pool", "TCP", "connection", "pool"]
homepage = "http://github.com/tailhook/tk-pool"
documentation = "http://docs.rs/tk-pool"
version = "0.1.0"
authors = ["paul@colomiets.name"]

[dependencies]
futures = "0.1.1"
abstract-ns = { git="git://github.com/tailhook/abstract-ns", rev="9de9000" }
tokio-core = { git="git://github.com/tailhook/tokio-core", branch="intervals" }
tokio-proto = { git="git://github.com/tokio-rs/tokio-proto", rev="a0998dc" }
tokio-service = { git="git://github.com/tokio-rs/tokio-service", rev="6d7cf21" }
quick-error = "1.1.0"

[dev-dependencies]
argparse = "0.2.1"
env_logger = "0.3.5"
tokio-redis = { git="git://github.com/tailhook/tokio-redis", rev="ffd4cb1" }
ns-dns-tokio = { git = "https://github.com/tailhook/abstract-ns", rev="9de9000" }

[replace]
"tokio-service:0.1.0" = { git="git://github.com/tokio-rs/tokio-service", rev="6d7cf21" }
"tokio-core:0.1.0" = { git="git://github.com/tailhook/tokio-core", branch="intervals" }

[lib]
name = "tk_pool"
